### ISSUE TITLE
Exception in the Client while pushing files

### ISSUE THREAD

**Issue by srivas-ksh** [Azure-Samples/app-service-mobile-dotnet-todo-list-files#4]
Hi ,

I ran the client and was able to successfully link a image to a item, However when next time i run the application , it give an exception while calling PushFileChangesAsync(). The details of the exception are below
**Message**: An exception of type 'System.MissingMethodException' occurred in mscorlib.dll but was not handled in user code
**Additional Info**: Method not found: 'System.Threading.Tasks.Task Microsoft.WindowsAzure.Storage.Blob.CloudBlockBlob.UploadFromStreamAsync(System.IO.Stream)

Thanks.

**Comment by lindydonna** [comment]
This is a bug in the Azure Storage library. Please upgrade to version 7.0.1-preview. We have a bug in our SDK to update our dependency: https://github.com/Azure/azure-mobile-apps-net-files-client/issues/47
