### ISSUE TITLE
PullAsync triggers an Update with FileSyncHandler while file wasn't modified

### ISSUE THREAD

**Issue by FrancoisM** [Azure-Samples/app-service-mobile-dotnet-todo-list-files#5]
Hi,

I encounter the following two issues with that sample.

1) If I add a file within the client and then sync, the file is pushed in Azure storage but locally in the table _filemetadata the lastModified field for that file is null. Then if I call another sync, it certainly compares lastModified in _filemetadata with LastModified in the cloud and it triggers a useless pull. Moreover, lastModified in _fileMetadata is a localized (based on the client language) string DateTimeOffset whereas in the cloud it is a DateTime based on the server time (which is not even UTC).

2) Moreover, pulling a file triggers table.DownloadFileAsync. On iOS it actually overwrites the local file with an empty one (whereas in azure storage the file is fine and not empty) and then the app crashes. I guess the file is open for writting and there is a swallowed exception somewhere which leads to the file being empty. I found that this issue is actually raised here:
https://github.com/Azure/azure-mobile-apps-net-files-client/issues/33

**Comment by lindydonna** [comment]
@FrancoisM Just saw the issues now--sorry about the delay!  These are both issues with the SDK, not the sample. If they aren't both covered by issue 33, could you file a new issue in the client SDK repo?
